---
- hosts: all
  sudo: true
  tasks:

    - name: Update apt
      apt: update_cache=yes

    - name: Install nodejs
      apt: name=nodejs state=present

    - name: Install lynx
      apt: name=lynx-cur state=present

    - name: GPG key
      command: gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3

    - name: Install RVM with Ruby
      shell: curl -sSL https://get.rvm.io | bash -s stable --ruby

    - name: Install Jekyll
      shell: '/bin/bash --login -c "gem install jekyll"'

